const mongoose = require("mongoose");

// Define the schema
const secondSemSchema = new mongoose.Schema({
  usn: { type: String, unique: true, index: true },
  name: String,
  gender: String,
  subject1: String,
  internal1: Number,
  external1: Number,
  total1: Number,
  grade1: Number,
  credit1: Number,
  subject2: String,
  internal2: Number,
  external2: Number,
  total2: Number,
  grade2: Number,
  credit2: Number,
  subject3: String,
  internal3: Number,
  external3: Number,
  total3: Number,
  grade3: Number,
  credit3: Number,
  subject4: String,
  internal4: Number,
  external4: Number,
  total4: Number,
  grade4: Number,
  credit4: Number,
  subject5: String,
  internal5: Number,
  external5: Number,
  total5: Number,
  grade5: Number,
  credit5: Number,
  subject6: String,
  internal6: Number,
  external6: Number,
  total6: Number,
  grade6: Number,
  credit6: Number,
  subject7: String,
  internal7: Number,
  external7: Number,
  total7: Number,
  grade7: Number,
  credit7: Number,
  subject8: String,
  internal8: Number,
  external8: Number,
  total8: Number,
  grade8: Number,
  credit8: Number,
  subject9: String,
  internal9: Number,
  external9: Number,
  total9: Number,
  grade9: Number,
  credit9: Number,
  calculatedPercentage: Number,
  calculatedSGPA: Number,
  total: Number,
  result: String,
});

// Create the model
const SecondSem = mongoose.model("SecondSem", secondSemSchema);

module.exports = SecondSem;
